#either use this or product-deployment and product-service in the same folder
apiVersion:                  v1
kind:                        Service
metadata:
  name:                      product-service
spec:
  selector:
    app:                     product-service
  ports:
    - protocol:              TCP
    # Port accessible inside cluster
      port:                  9991
    # Port to forward inside the pod
      targetPort:            9991
    # Port accessible outside cluster
      nodePort:              30004
  type:                      LoadBalancer

---
apiVersion:                  extensions/v1beta1
kind:                        Deployment
metadata:
  name:                      product-service
spec:
  replicas:                  3
  template:
    metadata:
      labels:
        app:                 product-service
    spec:
      containers:
      - name:                product-service
        image:               mootezelj/product-service:0.0.1-SNAPSHOT
        ports:
        - containerPort:     9991
        env:
        - name:              SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name:          product-service
              key:           server.port
