apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-service
  ports:
    - protocol: TCP
    # Port accessible inside cluster
      port: 9991
    # Port to forward inside the pod
      targetPort: 9991
    # Port accessible outside cluster
      nodePort: 30004
  type: LoadBalancer
