#Order deployment (Working fine)
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: mootezelj/order-service:0.0.1-SNAPSHOT
        ports:
        - containerPort: 9993
        env:
        - name: SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: order-service
              key: server.port
