apiVersion: v1
kind: Service
metadata:
  name: jwt-service
spec:
  selector:
    app: jwt-service
  ports:
    - protocol: TCP
    # Port accessible inside cluster
      port: 9995
    # Port to forward inside the pod
      targetPort: 9995
    # Port accessible outside cluster
      nodePort: 30009
  type: LoadBalancer
