#taken from customer-service-deployment.yml

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: customer-service
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: customer-service
    spec:
      containers:
      - name: customer-service
        image: mootezelj/customer-service:0.0.1-SNAPSHOT
        ports:
        - containerPort: 9992
        env:
        - name: SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: customer-service
              key: server.port
