#mix of service and deployment

apiVersion: v1
kind: Service
metadata:
  name: customer-service-service
spec:
  selector:
    app: customer-service
  ports:
    - protocol: TCP
    # Port accessible inside cluster
      port: 9992
    # Port to forward inside the pod
      targetPort: 9992
    # Port accessible outside cluster
      nodePort: 30005
  type: LoadBalancer



---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: customer-service-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: customer-service
    spec:
      containers:
      - name: customer-service
        image: mootezelj/customer-service:0.0.1-SNAPSHOT
        ports:
        - containerPort: 9992
        env:
        - name: SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: customer-service
              key: server.port
